export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const GET_DETAILED_STATEMENT = 'GET_DETAILED_STATEMENT';
export const UPDATE_DETAILED_STATEMENT = 'UPDATE_DETAILED_STATEMENT';
export const GET_BENIFIERS = 'GET_BENIFIERS';
export const UPDATE_BENIFIERS = 'UPDATE_BENIFIERS';